apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l7t6rb6yp-python
  janus-idp.io/tekton: l7t6rb6yp-python
  backstage.io/kubernetes-id: l7t6rb6yp-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: l7t6rb6yp-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
